name: iOS CI

on:
  push:
    branches: [ develop, release ]
  pull_request:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        run: ./.github/prepare-workflow
      - name: Run lint
        run: swiftlint --reporter "emoji"
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        name:
          - "iPhone 12"
          - "iPad Pro (9.7-inch)"
        os-version:
          - "16.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        run: ./.github/prepare-workflow
      - name: Build
        run: xcodebuild build -scheme Habitica -destination "platform=iOS Simulator,name=${{ matrix.name }},OS=${{ matrix.os-version }}"
  unit-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        name:
          - "iPhone 12"
          - "iPad Pro (9.7-inch)"
        os-version:
          - "16.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        run: ./.github/prepare-workflow
      - name: Build
        run: xcodebuild clean test -scheme 'Habitica' -destination 'platform=iOS Simulator,name=${{ matrix.name }},OS=${{ matrix.os-version }}' -testPlan "Unit Tests" -showBuildTimingSummary
  ui-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        name:
          - "iPhone 8"
          - "iPhone 11"
          - "iPhone 13 Pro Max"
          - "iPad Pro (9.7-inch)"
        os-version:
          - "16.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        run: ./.github/prepare-workflow
      - name: Build
        run: xcodebuild clean test -scheme 'Habitica' -destination 'platform=iOS Simulator,name=${{ matrix.name }},OS=${{ matrix.os-version }}' -testPlan "UI Tests" -showBuildTimingSummary
